server:
  port: 8001
  servlet:
    context-path: /user
spring:
  application:
    name: user-security
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 #配置Nacos地址
  sleuth:
    sampler:
      #采样值介于0到1之间，1则代表全部采样
      probability: 1
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource #当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver #mysql驱动包
    url: jdbc:mysql://localhost:3306/cloud?usrUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root

#eureka:
#  client:
#    #表示是否将自己注册进EurekaServer，默认为true
#    register-with-eureka: true
#    #是否从EurekaServer中抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
#    fetchRegistry: true
#    service-url:
#      defaultZone: http://localhost:7001/eureka #单机版
##      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka #集群版
#  instance:
#    instance-id: usersecurity #修改Status名称
#    prefer-ip-address: true #访问路径可以显示IP地址
#    #Eureka客户端向服务端发送心跳的时间间隔，单位为秒(默认30)
#    #lease-renewal-interval-in-seconds: 1
#    #Eureka服务端在收到最后一次心跳后等待的时间上限，单位为秒(默认90)，超时剔除服务
#    #lease-expiration-duration-in-seconds: 2

mybatis:
  mapperlocations: classpath:mapper/*.xml
  type-aliases-package: com.com.springcloud.entities #所有Entity别名类所在包

ali:
  Id: LTAI4G2x4PCxdK6YGs8quSnp
  key: 19EkCkF8e63tcpGAlGXkgUGRq7qFvP