server:
  port: 8000
spring:
  #给项目来个名字
  application:
    name: auth-server
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 #配置Nacos地址
    sleuth:
      sampler:
        probability: 1
    gateway:
      discovery:
        locator:
          enabled: true #表明gateway开启服务注册和发现的功能，并且spring cloud gateway自动根据服务发现为每一个服务创建了一个router，# 这个router将以服务名开头的请求路径转发到对应的服务
#          lower-case-service-id: true #将请求路径上的服务名配置为小写（因为服务注册的时候，向注册中心注册时将服务名转成大写的了,比如以/service-hi/*的请求路径被路由转发到服务名为service-hi的服务上
      routes:
      - id: test-id
        uri: lb://email-sms-server
#        order: -1
        predicates:
          - Path=/api2/**
#        filters:
#          - StripPrefix=1
  redis:
    host: 127.0.0.1
    client-name: root
    timeout: 1000
    password:
  #配置rabbitMq 服务器
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: 123321
    #虚拟host 可以不设置,使用server默认host
  #    virtual-host: JCcccHost
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource #当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver #mysql驱动包
    url: jdbc:mysql://localhost:3306/spring-security?usrUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  profiles:
    active: dev