server:
  port: 8000
spring:
  #给项目来个名字
  application:
    name: auth-server
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 #配置Nacos地址
    sleuth:
      sampler:
        probability: 1
  redis:
    timeout: 5000
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: -1
    password:
  #配置rabbitMq 服务器
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: root
    password:
    #虚拟host 可以不设置,使用server默认host
  #    virtual-host: JCcccHost
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource #当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver #mysql驱动包
    url: jdbc:mysql://localhost:3306/spring-security?usrUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  profiles:
    active: dev