spring:
  application:
    name: mongoDb-test
  data:
    mongodb:
      database: articledb
      host: 127.0.0.1
#      password:
#      username:
      port: 27017
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource #当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver #mysql驱动包
    url: jdbc:mysql://localhost:3306/cloud?usrUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
server:
  port: 8870