server:
  port: 8083


#eureka:
#  client:
#    #表示是否将自己注册进EurekaServer，默认为true
#    register-with-eureka: true
#    #是否从EurekaServer中抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
#    fetchRegistry: true
#    service-url:
#      defaultZone: http://localhost:7001/eureka #单机版
##      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka #集群版
#  instance:
#      instance-id: ui-feign-consumer
#设置feign客户端超时时间(OpenFeign默认支持ribbon)
ribbon:
  #指的是建立连接所用的时间，适用于网络状况正常的情况下,两端连接所用的时间
  ReadTimeout: 5000
  #指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 5000



#
logging:
  level:
    # feign日志以什么级别监控哪个接口
    com.springcloud.openfeign.service.UserFeignService.java: debug
feign:
  hystrix:
    enabled: true
spring:
  application:
    name: ui-openfeign-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 #配置Nacos地址